In [1]:
from tradepy.data.loader import load_future
from tradepy.config.config import load_config, load_symbols, load_feature_config
from tradepy.data.cleaner import add_trading_date_by_gap
from tradepy.data.resampler import resample_ohlcv, daily_ohlcv_cummulative
from tradepy.features.generate import generate_features

In [2]:
symbols = load_symbols()

In [3]:
symbols

['AD',
 'BP',
 'CL',
 'EC',
 'ES',
 'GC',
 'MFXI',
 'NG',
 'NQ',
 'YM',
 'ZB',
 'ZN',
 'ZS']

In [4]:
ASSET = symbols[4]

In [5]:
cfg = load_config()

In [6]:
MINUTES             = cfg['sampling_minutes']        # 240
RETURN_HORIZON_MIN  = cfg['return_horizon_min']      # 2880

In [7]:
df, spec = load_future(ASSET)

In [8]:
df = add_trading_date_by_gap(df)

In [9]:
df

,ticker,per,date,time,open,high,low,close,volume,openint,datetime,session_id,trading_date
0,ES,I,1997-09-10,07:08:00,934.00,934.00,934.00,934.00,1,0,1997-09-10 07:08:00,0,1997-09-10
1,ES,I,1997-09-10,07:15:00,933.75,933.75,933.75,933.75,1,0,1997-09-10 07:15:00,0,1997-09-10
2,ES,I,1997-09-10,08:10:00,933.75,933.75,933.75,933.75,1,0,1997-09-10 08:10:00,0,1997-09-10
3,ES,I,1997-09-10,08:13:00,934.00,934.00,934.00,934.00,1,0,1997-09-10 08:13:00,0,1997-09-10
4,ES,I,1997-09-10,08:20:00,933.75,933.75,933.75,933.75,1,0,1997-09-10 08:20:00,0,1997-09-10
...,...,...,...,...,...,...,...,...,...,...,...,...,...
8631144,ES,I,2026-01-19,06:57:00,6917.00,6917.00,6916.75,6916.75,26,0,2026-01-19 06:57:00,5073,2026-01-19
8631145,ES,I,2026-01-19,06:58:00,6917.00,6917.00,6916.75,6917.00,33,0,2026-01-19 06:58:00,5073,2026-01-19
8631146,ES,I,2026-01-19,06:59:00,6917.00,6917.50,6916.75,6916.75,112,0,2026-01-19 06:59:00,5073,2026-01-19
8631147,ES,I,2026-01-19,07:00:00,6916.75,6917.00,6916.25,6916.75,64,0,2026-01-19 07:00:00,5073,2026-01-19
8631148,ES,I,2026-01-19,07:01:00,6916.75,6917.25,6916.50,6917.00,33,0,2026-01-19 07:01:00,5073,2026-01-19

In [10]:
df_resampled = resample_ohlcv(df, period=f"{MINUTES}min")
df_cumulative = daily_ohlcv_cummulative(df_resampled)

In [11]:
config = load_feature_config()

In [12]:
config["global"]["sampling_minutes"] = MINUTES
config["global"]["return_horizon_min"] = RETURN_HORIZON_MIN
config["global"]["tick_size"] = spec["tick_size"]

In [13]:
generate_features(df_cumulative, config)

,datetime,open,high,low,close,volume,openint,ticker,per,trading_date,...,bb_percent_b,atr,vpt_norm,rolling_skew_10,rolling_kurt_10,rolling_skew_20,rolling_kurt_20,atr_norm,atr_z,vol_vol_ratio
0,1997-10-15 12:00:00,972.75,973.50,972.5,972.75,19,0.0,ES,240min,1997-10-15,...,0.162997,5.931037,-0.000090,-0.526029,0.043288,-0.635229,-0.135448,0.006097,0.531223,3.203487
1,1997-10-15 16:00:00,973.00,974.00,968.0,970.00,779,0.0,ES,240min,1997-10-15,...,0.010388,5.940232,-0.002270,-0.210722,-0.160281,-0.522554,-0.324578,0.006124,0.487486,131.139651
2,1997-10-15 20:00:00,970.25,975.25,970.0,973.50,1762,0.0,ES,240min,1997-10-15,...,0.282258,5.848201,0.006531,-0.236955,-0.425633,-0.715526,0.275918,0.006007,0.380050,301.289215
3,1997-10-16 00:00:00,973.25,976.75,972.0,973.50,1119,0.0,ES,240min,1997-10-15,...,0.301507,5.701775,0.000000,-0.573366,0.549119,-0.729127,0.545999,0.005857,0.264258,196.254691
4,1997-10-16 08:00:00,972.75,972.75,972.5,972.75,5,0.0,ES,240min,1997-10-16,...,0.265999,5.074871,-0.000004,-0.454985,0.487238,-0.685419,0.498849,0.005217,-0.591351,0.985247
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
41385,2026-01-16 16:00:00,7002.75,7004.25,6981.5,6982.00,228308,0.0,ES,240min,2026-01-16,...,0.449616,21.231328,-0.096893,-1.241482,0.407076,-0.317432,-1.073128,0.003041,-1.202120,10753.354520
41386,2026-01-16 20:00:00,6982.00,6995.00,6960.5,6987.75,561713,0.0,ES,240min,2026-01-16,...,0.534497,23.000485,0.066201,-1.366278,0.665366,-0.444868,-1.027283,0.003292,-0.474008,24421.789881
41387,2026-01-17 00:00:00,6988.00,6997.50,6973.5,6977.75,345435,0.0,ES,240min,2026-01-16,...,0.421141,23.133753,-0.070846,-0.920414,-0.441789,-0.293451,-1.186004,0.003315,-0.446524,14932.077658
41388,2026-01-19 04:00:00,6918.25,6935.00,6911.0,6922.00,70217,0.0,ES,240min,2026-01-19,...,-0.134196,28.949253,-0.081048,-1.375018,1.612621,-1.329610,2.344234,0.004182,2.082399,2425.520287
41389,2026-01-19 08:00:00,6922.00,6922.75,6912.5,6917.00,16690,0.0,ES,240min,2026-01-19,...,-0.058576,26.456019,-0.001743,-1.366598,1.876764,-1.268188,2.356348,0.003825,0.889922,630.858329