In [17]:
from tradepy.data.loader import load_future
from tradepy.config.config import load_config, load_symbols, load_feature_config
from tradepy.data.cleaner import add_trading_date_by_gap
from tradepy.data.resampler import resample_ohlcv, daily_ohlcv_cummulative
from tradepy.features.generate import generate_features
from tradepy.features.quality_check import data_quality_report

In [18]:
symbols = load_symbols()

In [19]:
symbols

['AD',
 'BP',
 'CL',
 'EC',
 'ES',
 'GC',
 'MFXI',
 'NG',
 'NQ',
 'YM',
 'ZB',
 'ZN',
 'ZS']

In [20]:
ASSET = symbols[4]

In [21]:
cfg = load_config()

In [22]:
MINUTES             = cfg['sampling_minutes']        # 240
RETURN_HORIZON_MIN  = cfg['return_horizon_min']      # 2880

In [23]:
df, spec = load_future(ASSET)

In [24]:
df["datetime"] = df["datetime_utc"]

In [25]:
df = add_trading_date_by_gap(df)

In [26]:
df

,ticker,per,date,time,open,high,low,close,volume,openint,datetime,datetime_utc,session_id,trading_date
0,ES,I,1997-09-10,07:08:00,934.00,934.00,934.00,934.00,1,0,1997-09-10 13:08:00,1997-09-10 13:08:00,0,1997-09-10
1,ES,I,1997-09-10,07:15:00,933.75,933.75,933.75,933.75,1,0,1997-09-10 13:15:00,1997-09-10 13:15:00,0,1997-09-10
2,ES,I,1997-09-10,08:10:00,933.75,933.75,933.75,933.75,1,0,1997-09-10 14:10:00,1997-09-10 14:10:00,0,1997-09-10
3,ES,I,1997-09-10,08:13:00,934.00,934.00,934.00,934.00,1,0,1997-09-10 14:13:00,1997-09-10 14:13:00,0,1997-09-10
4,ES,I,1997-09-10,08:20:00,933.75,933.75,933.75,933.75,1,0,1997-09-10 14:20:00,1997-09-10 14:20:00,0,1997-09-10
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8631144,ES,I,2026-01-19,06:57:00,6917.00,6917.00,6916.75,6916.75,26,0,2026-01-19 12:57:00,2026-01-19 12:57:00,5073,2026-01-19
8631145,ES,I,2026-01-19,06:58:00,6917.00,6917.00,6916.75,6917.00,33,0,2026-01-19 12:58:00,2026-01-19 12:58:00,5073,2026-01-19
8631146,ES,I,2026-01-19,06:59:00,6917.00,6917.50,6916.75,6916.75,112,0,2026-01-19 12:59:00,2026-01-19 12:59:00,5073,2026-01-19
8631147,ES,I,2026-01-19,07:00:00,6916.75,6917.00,6916.25,6916.75,64,0,2026-01-19 13:00:00,2026-01-19 13:00:00,5073,2026-01-19
8631148,ES,I,2026-01-19,07:01:00,6916.75,6917.25,6916.50,6917.00,33,0,2026-01-19 13:01:00,2026-01-19 13:01:00,5073,2026-01-19

In [27]:
df_resampled = resample_ohlcv(df, period=f"{MINUTES}min")
df_cumulative = daily_ohlcv_cummulative(df_resampled)

In [28]:
config = load_feature_config()

In [29]:
config["global"]["sampling_minutes"] = MINUTES
config["global"]["return_horizon_min"] = RETURN_HORIZON_MIN
config["global"]["tick_size"] = spec["tick_size"]

In [30]:
df_final = generate_features(df_cumulative, config)

In [31]:
df_final

,datetime,open,high,low,close,volume,openint,ticker,per,trading_date,...,fib_dist_786,nearest_fib_level,dist_to_nearest_fib,swing_extension,bars_between_swing_highs,bars_between_swing_lows,swing_high_velocity,swing_low_velocity,bars_between_swings,swing_cycle_ratio
0,1997-09-10 16:00:00,934.00,934.25,933.75,934.25,11,0.0,ES,240min,1997-09-10,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,1997-09-10 20:00:00,934.00,934.00,930.50,931.25,54,0.0,ES,240min,1997-09-10,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,1997-09-11 00:00:00,931.25,932.75,925.00,928.00,1305,0.0,ES,240min,1997-09-10,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,1997-09-11 04:00:00,927.75,930.25,918.00,918.50,1550,0.0,ES,240min,1997-09-11,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,1997-09-11 08:00:00,918.50,919.50,914.50,914.75,187,0.0,ES,240min,1997-09-11,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
43757,2026-01-17 04:00:00,6986.75,6997.50,6976.75,6980.75,391672,0.0,ES,240min,2026-01-17,...,-0.599953,0.236,-0.049953,-0.813953,3.0,7.0,10.75,6.071429,3.0,0.333333
43758,2026-01-17 08:00:00,6980.75,6982.25,6973.50,6977.75,96050,0.0,ES,240min,2026-01-17,...,-0.415032,0.382,-0.011032,-0.629032,3.0,5.0,10.75,9.300000,2.0,1.000000
43759,2026-01-19 08:00:00,6918.25,6935.00,6911.00,6922.25,49191,0.0,ES,240min,2026-01-19,...,-1.608581,0.236,-1.058581,-1.822581,3.0,5.0,10.75,9.300000,2.0,1.500000
43760,2026-01-19 12:00:00,6922.50,6927.00,6914.25,6914.50,31659,0.0,ES,240min,2026-01-19,...,-1.775247,0.236,-1.225247,-1.989247,3.0,5.0,10.75,9.300000,2.0,2.000000
43761,2026-01-19 16:00:00,6914.50,6921.00,6912.50,6917.00,6057,0.0,ES,240min,2026-01-19,...,-0.723500,0.236,-0.173500,-0.937500,3.0,3.0,10.75,32.000000,5.0,1.000000

In [32]:
data_quality_report(df_final)

Data Quality Report
 - rows: 43762, cols: 188
 - top 20 NaN fractions:
swing_low              0.848224
swing_low_price        0.848224
swing_low_strength     0.848224
swing_high             0.846374
swing_high_price       0.846374
swing_high_strength    0.846374
ad_z                   0.026484
cmf                    0.026461
ad_sma_10              0.016613
ad_roc_10              0.003999
ad_roc_5               0.003839
ad_delta               0.003748
ad_dir                 0.003748
ad_rel                 0.002651
close_location         0.001897
body_pct               0.001897
wick_ratio             0.001897
volume_range           0.001897
obv_norm               0.001897
ad                     0.001897
dtype: float64

Suggestions:
 - Many columns have >50% NaNs; consider dropping or re-engineering them.
 - Drop or fix constant columns: ['openint', 'ticker', 'per', 'minute', 'minute_sin', 'minute_cos', 'is_post_break_hour', 'is_NY_open_hour']
 - `rolling_slope` may be slow; consider vectorized replacement or numba.
 - To avoid fragmentation, build new columns in a dict and `pd.concat` once per group.

{'rows': 43762,
 'cols': 188,
 'na_fraction': {'swing_low': 0.848224486997852,
  'swing_low_price': 0.848224486997852,
  'swing_low_strength': 0.848224486997852,
  'swing_high': 0.846373566107582,
  'swing_high_price': 0.846373566107582,
  'swing_high_strength': 0.846373566107582,
  'ad_z': 0.026484164343494355,
  'cmf': 0.026461313468305835,
  'ad_sma_10': 0.016612586262053836,
  'ad_roc_10': 0.003998903157990951,
  'ad_roc_5': 0.003838947031671313,
  'ad_delta': 0.003747543530917234,
  'ad_dir': 0.003747543530917234,
  'ad_rel': 0.0026507015218682874,
  'close_location': 0.0018966226406471368,
  'body_pct': 0.0018966226406471368,
  'wick_ratio': 0.0018966226406471368,
  'volume_range': 0.0018966226406471368,
  'obv_norm': 0.0018966226406471368,
  'ad': 0.0018966226406471368,
  'clv': 0.0018966226406471368,
  'ad_norm': 0.0018966226406471368,
  'upper_wick_pct': 0.0018966226406471368,
  'lower_wick_pct': 0.0018966226406471368,
  'pct_above_ma_50': 0.0011196928842374663,
  'obv_z': 0.0007769297564096705,
  'relative_volume': 0.0007540788812211508,
  'obv_rel': 0.0007540788812211508,
  'mfi': 0.0007540788812211508,
  'volume_z': 0.0007540788812211508,
  'adx': 0.0006169736300900325,
  'return_lag_20': 0.0004798683789589141,
  'return_z_20': 0.0004570175037703944,
  'atr_z': 0.0004570175037703944,
  'rolling_kurt_20': 0.0004570175037703944,
  'rolling_skew_20': 0.0004570175037703944,
  'swing_low_velocity': 0.0004570175037703944,
  'hv': 0.0004570175037703944,
  'return_std_20': 0.0004570175037703944,
  'return_mean_20': 0.0004570175037703944,
  'realized_vol_20': 0.0004570175037703944,
  'roc_20': 0.0004570175037703944,
  'volume_sum_20': 0.0004341666285818747,
  'avg_volume': 0.0004341666285818747,
  'bb_std': 0.0004341666285818747,
  'bb_middle': 0.0004341666285818747,
  'bb_upper': 0.0004341666285818747,
  'bb_lower': 0.0004341666285818747,
  'cci': 0.0004341666285818747,
  'sma_20': 0.0004341666285818747,
  'bb_width': 0.0004341666285818747,
  'bb_percent_b': 0.0004341666285818747,
  'pct_above_ma_20': 0.0004341666285818747,
  'swing_high_velocity': 0.00041131575339335496,
  'bars_between_swing_highs': 0.00041131575339335496,
  'slowd': 0.00038846487820483523,
  'slowk': 0.00038846487820483523,
  'fib_dist_786': 0.0003427631278277958,
  'fib_dist_618': 0.0003427631278277958,
  'retracement_ratio': 0.0003427631278277958,
  'fib_dist_5': 0.0003427631278277958,
  'fib_dist_382': 0.0003427631278277958,
  'fib_dist_236': 0.0003427631278277958,
  'close_in_swing_range': 0.0003427631278277958,
  'nearest_fib_level': 0.0003427631278277958,
  'swing_extension': 0.0003427631278277958,
  'dist_to_nearest_fib': 0.0003427631278277958,
  'cmo': 0.0003199122526392761,
  'swing_range': 0.0003199122526392761,
  'last_swing_high_strength': 0.0003199122526392761,
  'last_swing_high_bar': 0.0003199122526392761,
  'bars_between_swings': 0.0003199122526392761,
  'bars_since_swing_high': 0.0003199122526392761,
  'swing_range_pct': 0.0003199122526392761,
  'rsi': 0.0003199122526392761,
  'last_swing_high_price': 0.0003199122526392761,
  'dist_to_last_swing_high': 0.0003199122526392761,
  'swing_cycle_ratio': 0.0003199122526392761,
  'efi': 0.00029706137745075635,
  'range_mean': 0.00029706137745075635,
  'williams_r': 0.00029706137745075635,
  'return_horizon_2880m': 0.0002742105022622366,
  'log_return_horizon_2880m': 0.0002742105022622366,
  'return_lag_10': 0.00025135962707371694,
  'rolling_kurt_10': 0.0002285087518851972,
  'kama': 0.0002285087518851972,
  'obv_roc_10': 0.0002285087518851972,
  'roc_10': 0.0002285087518851972,
  'return_z_10': 0.0002285087518851972,
  'return_mean_10': 0.0002285087518851972,
  'rolling_skew_10': 0.0002285087518851972,
  'return_std_10': 0.0002285087518851972,
  'obv_sma_10': 0.00020565787669667748,
  'bars_between_swing_lows': 0.00020565787669667748,
  'slope_10': 0.00020565787669667748,
  'last_swing_low_strength': 0.0001371052511311183,
  'dist_to_last_swing_low': 0.0001371052511311183,
  'bars_since_swing_low': 0.0001371052511311183,
  'last_swing_low_price': 0.0001371052511311183,
  'return_lag_5': 0.0001371052511311183,
  'last_swing_low_bar': 0.0001371052511311183,
  'return_mean_5': 0.0001142543759425986,
  'return_z_5': 0.0001142543759425986,
  'return_std_5': 0.0001142543759425986,
  'roc_5': 0.0001142543759425986,
  'obv_roc_5': 0.0001142543759425986,
  'tr_dir': 4.5701750377039444e-05,
  'return_lag_1': 4.5701750377039444e-05,
  'vpt_norm': 2.2850875188519722e-05,
  'atr': 2.2850875188519722e-05,
  'atr_norm': 2.2850875188519722e-05,
  'vol_vol_ratio': 2.2850875188519722e-05,
  'log_return': 2.2850875188519722e-05,
  'obv_delta': 2.2850875188519722e-05,
  'return': 2.2850875188519722e-05,
  'volume_delta': 2.2850875188519722e-05,
  'obv_dir': 2.2850875188519722e-05,
  'roc_1': 2.2850875188519722e-05,
  'vpt': 2.2850875188519722e-05,
  'true_range': 2.2850875188519722e-05,
  'ema_20': 0.0,
  'histogram': 0.0,
  'macd': 0.0,
  'signal': 0.0,
  'ad_ema_10': 0.0,
  'obv_ema_10': 0.0,
  'range': 0.0,
  'obv': 0.0,
  'ticker': 0.0,
  'openint': 0.0,
  'volume': 0.0,
  'volume_cum': 0.0,
  'ema_slow': 0.0,
  'ema_fast': 0.0,
  'dema': 0.0,
  'close': 0.0,
  'datetime': 0.0,
  'open': 0.0,
  'high': 0.0,
  'low': 0.0,
  'high_cum': 0.0,
  'open_day': 0.0,
  'trading_date': 0.0,
  'per': 0.0,
  'low_cum': 0.0,
  'seconds_since_midnight': 0.0,
  'is_post_break_hour': 0.0,
  'week_of_month': 0.0,
  'is_ny': 0.0,
  'is_overlap': 0.0,
  'session_progress': 0.0,
  'is_london': 0.0,
  'dist_open_day_ticks': 0.0,
  'dist_low_cum_ticks': 0.0,
  'range_ticks': 0.0,
  'dist_high_cum_ticks': 0.0,
  'volume_price': 0.0,
  'body': 0.0,
  'upper_wick_ticks': 0.0,
  'lower_wick_ticks': 0.0,
  'is_doji': 0.0,
  'vwap': 0.0,
  'body_ticks': 0.0,
  'is_NY_open_hour': 0.0,
  'month_sin': 0.0,
  'day_cos': 0.0,
  'is_prev_break_hour': 0.0,
  'month_cos': 0.0,
  'day_sin': 0.0,
  'dow_cos': 0.0,
  'minute_cos': 0.0,
  'dow_sin': 0.0,
  'dayofweek': 0.0,
  'minute': 0.0,
  'minute_sin': 0.0,
  'hour_cos': 0.0,
  'hour_sin': 0.0,
  'is_month_end': 0.0,
  'month': 0.0,
  'day': 0.0,
  'vol_vs_body': 0.0,
  'vol_per_tick': 0.0,
  'hour': 0.0,
  'vol_weight_intraday': 0.0,
  'market_structure': 0.0,
  'swing_trend_score': 0.0,
  'swing_high_type': 0.0,
  'swing_low_type': 0.0},
 'top_na': {'swing_low': 0.848224486997852,
  'swing_low_price': 0.848224486997852,
  'swing_low_strength': 0.848224486997852,
  'swing_high': 0.846373566107582,
  'swing_high_price': 0.846373566107582,
  'swing_high_strength': 0.846373566107582,
  'ad_z': 0.026484164343494355,
  'cmf': 0.026461313468305835,
  'ad_sma_10': 0.016612586262053836,
  'ad_roc_10': 0.003998903157990951,
  'ad_roc_5': 0.003838947031671313,
  'ad_delta': 0.003747543530917234,
  'ad_dir': 0.003747543530917234,
  'ad_rel': 0.0026507015218682874,
  'close_location': 0.0018966226406471368,
  'body_pct': 0.0018966226406471368,
  'wick_ratio': 0.0018966226406471368,
  'volume_range': 0.0018966226406471368,
  'obv_norm': 0.0018966226406471368,
  'ad': 0.0018966226406471368},
 'constant_columns': ['openint',
  'ticker',
  'per',
  'minute',
  'minute_sin',
  'minute_cos',
  'is_post_break_hour',
  'is_NY_open_hour'],
 'infinite_columns': [],
 'infinite_counts': {},
 'top_zero_fraction': {'openint': 1.0,
  'minute_sin': 1.0,
  'minute': 1.0,
  'is_doji': 0.8990905351674969,
  'is_overlap': 0.8338055847538961,
  'is_ny': 0.6672684063799643,
  'is_london': 0.4979434212330332,
  'market_structure': 0.36147799460719343,
  'swing_trend_score': 0.28003747543530916,
  'hour': 0.16669713450025136,
  'session_progress': 0.16669713450025136,
  'seconds_since_midnight': 0.16669713450025136,
  'hour_sin': 0.16669713450025136,
  'bars_since_swing_high': 0.1536264338924181,
  'bars_since_swing_low': 0.15177551300214798,
  'swing_cycle_ratio': 0.14190393492070746,
  'dow_sin': 0.1230519628901787,
  'dayofweek': 0.1230519628901787,
  'month_sin': 0.08237740505461359,
  'bars_between_swings': 0.07613911612814771},
 'object_unique_counts': {'ticker': 1, 'per': 1, 'trading_date': 8802},
 'describe': {'datetime': {'min': Timestamp('1997-09-10 16:00:00'),
   '25%': Timestamp('2005-06-13 09:00:00'),
   '50%': Timestamp('2012-05-09 02:00:00'),
   '75%': Timestamp('2019-03-18 23:00:00'),
   'max': Timestamp('2026-01-19 16:00:00')},
  'open': {'min': 674.5,
   '25%': 1194.0,
   '50%': 1482.0,
   '75%': 2834.75,
   'max': 7016.5},
  'high': {'min': 678.0,
   '25%': 1196.75,
   '50%': 1486.25,
   '75%': 2841.6875,
   'max': 7036.25},
  'low': {'min': 665.75,
   '25%': 1191.25,
   '50%': 1478.25,
   '75%': 2826.25,
   'max': 7005.75},
  'close': {'min': 674.5,
   '25%': 1194.25,
   '50%': 1482.375,
   '75%': 2834.75,
   'max': 7016.25},
  'volume': {'min': 0.0,
   '25%': 14372.5,
   '50%': 55135.5,
   '75%': 259501.5,
   'max': 3405275.0},
  'openint': {'min': 0.0, '25%': 0.0, '50%': 0.0, '75%': 0.0, 'max': 0.0},
  'open_day': {'min': 678.5,
   '25%': 1193.5,
   '50%': 1483.25,
   '75%': 2831.0,
   'max': 7013.5},
  'high_cum': {'min': 684.5,
   '25%': 1199.25,
   '50%': 1489.75,
   '75%': 2847.0,
   'max': 7036.25},
  'low_cum': {'min': 665.75,
   '25%': 1187.75,
   '50%': 1474.25,
   '75%': 2820.375,
   'max': 7004.75},
  'volume_cum': {'min': 0.0,
   '25%': 153172.5,
   '50%': 507112.0,
   '75%': 850206.5,
   'max': 6785368.0},
  'sma_20': {'min': 684.325,
   '25%': 1194.28125,
   '50%': 1480.4875,
   '75%': 2835.4,
   'max': 6993.925},
  'ema_20': {'min': 687.0640823545373,
   '25%': 1194.1869808331187,
   '50%': 1479.3782757922788,
   '75%': 2835.656493331385,
   'max': 6991.751989595565},
  'dema': {'min': 675.1044167600347,
   '25%': 1193.9645180650068,
   '50%': 1482.632340961618,
   '75%': 2834.5167147528714,
   'max': 7007.35530144308},
  'kama': {'min': 687.7464538277995,
   '25%': 1194.829510374927,
   '50%': 1480.632843101088,
   '75%': 2833.535531750862,
   'max': 6989.265673022371},
  'ema_fast': {'min': 682.665461065079,
   '25%': 1193.719630797541,
   '50%': 1479.8380534813246,
   '75%': 2835.38778031062,
   'max': 6998.58703154982},
  'ema_slow': {'min': 690.7265613069187,
   '25%': 1194.561893260307,
   '50%': 1478.564900519587,
   '75%': 2835.260611674163,
   'max': 6987.47190718947},
  'macd': {'min': -183.18273056644193,
   '25%': -3.4175368036643476,
   '50%': 1.6227221383230699,
   '75%': 5.794518614981428,
   'max': 59.45321433426034},
  'signal': {'min': -149.49439415552618,
   '25%': -3.10495947114124,
   '50%': 1.5544116975616329,
   '75%': 5.421627097220117,
   'max': 55.054891501217035},
  'histogram': {'min': -56.77056832133559,
   '25%': -1.3798537402846787,
   '50%': -0.07718187232095453,
   '75%': 1.3017530607698122,
   'max': 68.10676719640612},
  'adx': {'min': 6.6287499955149665,
   '25%': 19.459515645398263,
   '50%': 25.018890265939174,
   '75%': 32.04994810420877,
   'max': 71.49173533329947},
  'rsi': {'min': 7.761162443434133,
   '25%': 43.03842236301398,
   '50%': 53.51077508171953,
   '75%': 62.47629778322197,
   'max': 90.62048551163059},
  'slowk': {'min': -5.444163638420226e-13,
   '25%': 30.70175438596492,
   '50%': 60.36036036036062,
   '75%': 83.03127221037686,
   'max': 99.5774429100285},
  'slowd': {'min': 2.025016420105978,
   '25%': 31.439489375997805,
   '50%': 60.21146953405053,
   '75%': 82.28313492729687,
   'max': 99.24996709140753},
  'cmo': {'min': -100.0,
   '25%': -21.57894736842105,
   '50%': 6.177328843995511,
   '75%': 33.333333333333336,
   'max': 100.0},
  'williams_r': {'min': -100.0,
   '25%': -70.9090909090909,
   '50%': -39.189189189189186,
   '75%': -15.126050420168067,
   'max': -0.0},
  'cci': {'min': -559.2482329829371,
   '25%': -75.53518956275174,
   '50%': 29.46988087844953,
   '75%': 98.15607481022755,
   'max': 453.81526104418066},
  'roc_10': {'min': -0.14585012087026594,
   '25%': -0.006106842966471626,
   '50%': 0.0011864869285200808,
   '75%': 0.00787098795902813,
   'max': 0.2071366405570061},
  'roc_1': {'min': -0.06597896026963534,
   '25%': -0.0014184397163120588,
   '50%': 0.00014868230308895392,
   '75%': 0.0017059024223813335,
   'max': 0.09737210231814553},
  'roc_5': {'min': -0.12425595238095233,
   '25%': -0.004211117349803506,
   '50%': 0.0006202191440976002,
   '75%': 0.005244459482321107,
   'max': 0.12273587456069213},
  'roc_20': {'min': -0.1912247770999531,
   '25%': -0.008555008698745231,
   '50%': 0.0024315775523274796,
   '75%': 0.011857587952435189,
   'max': 0.19649761200818738},
  'bb_middle': {'min': 684.325,
   '25%': 1194.28125,
   '50%': 1480.4875,
   '75%': 2835.4,
   'max': 6993.925},
  'bb_std': {'min': 0.9937303455540796,
   '25%': 5.975484455794994,
   '50%': 9.785159278293996,
   '75%': 17.47006828626916,
   'max': 268.41447966676577},
  'bb_upper': {'min': 695.3023690636171,
   '25%': 1209.8947098210404,
   '50%': 1503.671322966868,
   '75%': 2870.6260112029186,
   'max': 7037.969850234305},
  'bb_lower': {'min': 659.0673808266337,
   '25%': 1178.0047692400371,
   '50%': 1460.6156512331463,
   '75%': 2798.378247258048,
   'max': 6957.68526460672},
  'true_range': {'min': 0.0,
   '25%': 4.0,
   '50%': 7.5,
   '75%': 14.0,
   'max': 523.0},
  'range': {'min': 0.0, '25%': 3.75, '50%': 7.25, '75%': 14.0, 'max': 523.0},
  'range_mean': {'min': 1.625,
   '25%': 5.535714285714286,
   '50%': 8.053571428571429,
   '75%': 13.875,
   'max': 176.92857142857142},
  'hv': {'min': 0.007599101201249858,
   '25%': 0.03596271691555311,
   '50%': 0.05263535590209821,
   '75%': 0.07732321030583804,
   'max': 0.5129321478547045},
  'realized_vol_20': {'min': 0.007410503224559216,
   '25%': 0.03602832748647465,
   '50%': 0.05261487094924235,
   '75%': 0.07704323150237442,
   'max': 0.5009403194151031},
  'obv': {'min': -17679221.0,
   '25%': -20132.5,
   '50%': 29750585.0,
   '75%': 81312211.25,
   'max': 102919179.0},
  'obv_norm': {'min': -40901132.0,
   '25%': -1982.1410256410256,
   '50%': 2953270.117647059,
   '75%': 7721370.533333333,
   'max': 120607590.0},
  'obv_roc_5': {'min': -734.4138851802403,
   '25%': -0.014568129135808405,
   '50%': 0.0001681182537451864,
   '75%': 0.013999088802188586,
   'max': 182.42857142857142},
  'obv_roc_10': {'min': -1812.2656875834446,
   '25%': -0.021229272355684697,
   '50%': 0.0004839984842530676,
   '75%': 0.02065312219127219,
   'max': 187.6967100349829},
  'obv_ema_10': {'min': -16052284.464491561,
   '25%': -20009.390193320607,
   '50%': 29723649.02722794,
   '75%': 81301446.52627179,
   'max': 102247069.21387812},
  'obv_sma_10': {'min': -16369679.9,
   '25%': -19053.7,
   '50%': 29709009.2,
   '75%': 81316808.8,
   'max': 102332876.8},
  'obv_z': {'min': -4.248529157249601,
   '25%': -0.974153335168081,
   '50%': 0.13483372921771197,
   '75%': 1.1060888496700454,
   'max': 4.1977192559126},
  'obv_dir': {'min': -1.0, '25%': -1.0, '50%': 1.0, '75%': 1.0, 'max': 1.0},
  'obv_rel': {'min': -74.04039693152228,
   '25%': -0.12747701457029928,
   '50%': 6.201861220902723,
   '75%': 18.407065773933077,
   'max': 67.33541974130355},
  'obv_delta': {'min': -3405275.0,
   '25%': -47506.0,
   '50%': 77.0,
   '75%': 58294.0,
   'max': 3210142.0},
  'vpt': {'min': -119096.04035308953,
   '25%': -59.598400825380445,
   '50%': 0.08417140358548317,
   '75%': 85.48756756756757,
   'max': 198701.3118374558},
  'clv': {'min': -1.0,
   '25%': -0.4666666666666667,
   '50%': 0.09090909090909091,
   '75%': 0.59375,
   'max': 1.0},
  'ad': {'min': -4639251.40115266,
   '25%': 9799440.217262136,
   '50%': 116376513.0596805,
   '75%': 279102462.00249183,
   'max': 418945370.5158069},
  'ad_norm': {'min': -14550228.256997343,
   '25%': 2069455.1921929857,
   '50%': 10645601.159751998,
   '75%': 26258088.21544146,
   'max': 328499660.43228173},
  'ad_roc_5': {'min': -174.84581363337125,
   '25%': -0.0023361683704180847,
   '50%': 0.00039533807055369685,
   '75%': 0.004167921475294156,
   'max': 3851.3511658491084},
  'ad_roc_10': {'min': -177.5217832160857,
   '25%': -0.0030835253815827968,
   '50%': 0.0008143709008296973,
   '75%': 0.00648377298323044,
   'max': 399.63179513158536},
  'ad_ema_10': {'min': -4460724.169765507,
   '25%': 9797461.055006469,
   '50%': 115972129.61425011,
   '75%': 278804085.2396662,
   'max': 418645406.67006},
  'ad_sma_10': {'min': -4306297.851393352,
   '25%': 10063210.77256288,
   '50%': 118351807.16543658,
   '75%': 282028917.9439373,
   'max': 418652666.70047224},
  'ad_z': {'min': -4.248529157249599,
   '25%': -0.7675224885844714,
   '50%': 0.5026885179589266,
   '75%': 1.2919684937575617,
   'max': 3.859867770102852},
  'ad_delta': {'min': -2566464.668161437,
   '25%': -17131.00000000745,
   '50%': 143.21590909091174,
   '75%': 30054.39113873616,
   'max': 2660254.162303664},
  'ad_dir': {'min': -1.0, '25%': -1.0, '50%': 1.0, '75%': 1.0, 'max': 1.0},
  'ad_rel': {'min': -16.715525637126884,
   '25%': 3.7614750618391515,
   '50%': 19.555300149008595,
   '75%': 63.066173548053385,
   'max': 279.78605129777725},
  'volume_range': {'min': 0.0,
   '25%': 2350.588932806324,
   '50%': 7125.185185185185,
   '75%': 23901.92380952381,
   'max': 193513.33333333334},
  'volume_price': {'min': 0.0,
   '25%': 6.650980406721622,
   '50%': 25.94339272318694,
   '75%': 115.3701446543347,
   'max': 3024.2229129662524},
  'mfi': {'min': 0.0,
   '25%': 33.45727108947182,
   '50%': 50.65518134176507,
   '75%': 68.74486899840628,
   'max': 100.0},
  'cmf': {'min': -0.8417216193609479,
   '25%': -0.08565050465290293,
   '50%': 0.059671693010476035,
   '75%': 0.20741478250364104,
   'max': 0.9555555555555558},
  'efi': {'min': -39196796.67450455,
   '25%': -346608.18815403344,
   '50%': 5672.9979851245025,
   '75%': 408604.53409970534,
   'max': 92863742.81213512},
  'vwap': {'min': 921.7189206492675,
   '25%': 1161.6178844764108,
   '50%': 1257.2905281347641,
   '75%': 1555.0159856532027,
   'max': 2316.454396887029},
  'avg_volume': {'min': 0.0,
   '25%': 112899.35,
   '50%': 189353.9,
   '75%': 269176.775,
   'max': 1038676.2},
  'relative_volume': {'min': 0.0,
   '25%': 0.11318390202890274,
   '50%': 0.3368861860770808,
   '75%': 1.9407592824363789,
   'max': 20.0},
  'volume_z': {'min': -1.1120715742392158,
   '25%': -0.6924188496775997,
   '50%': -0.5394488252912841,
   '75%': 0.8307982262674513,
   'max': 4.2485291572496005},
  'volume_sum_20': {'min': 0.0,
   '25%': 2257987.0,
   '50%': 3787078.0,
   '75%': 5383535.5,
   'max': 20773524.0},
  'volume_delta': {'min': -3105174.0,
   '25%': -90945.0,
   '50%': 872.0,
   '75%': 30849.0,
   'max': 2668935.0},
  'pct_above_ma_20': {'min': -0.11665439797774972,
   '25%': -0.004772972837889649,
   '50%': 0.001324064879179166,
   '75%': 0.006475598322958839,
   'max': 0.10265907310791618},
  'pct_above_ma_50': {'min': -0.18882665788111255,
   '25%': -0.0071102991877782145,
   '50%': 0.003192850473932718,
   '75%': 0.011041087870268603,
   'max': 0.10136954182524635},
  'slope_10': {'min': -71.64848484848486,
   '25%': -1.5515151515151515,
   '50%': -0.20454545454545456,
   '75%': 1.2,
   'max': 68.22727272727273},
  'tr_dir': {'min': -1.0, '25%': -1.0, '50%': 1.0, '75%': 1.0, 'max': 1.0},
  'body': {'min': 0.0, '25%': 1.0, '50%': 2.75, '75%': 6.75, 'max': 487.25},
  'wick_ratio': {'min': 0.0,
   '25%': 0.3333333333333333,
   '50%': 0.5454545454545454,
   '75%': 0.7631578947368421,
   'max': 1.0},
  'is_doji': {'min': 0.0, '25%': 0.0, '50%': 0.0, '75%': 0.0, 'max': 1.0},
  'body_ticks': {'min': -856.0,
   '25%': -10.0,
   '50%': 1.0,
   '75%': 12.0,
   'max': 1949.0},
  'range_ticks': {'min': 0.0,
   '25%': 15.0,
   '50%': 29.0,
   '75%': 56.0,
   'max': 2092.0},
  'upper_wick_ticks': {'min': 0.0,
   '25%': 2.0,
   '50%': 6.0,
   '75%': 13.0,
   'max': 930.0},
  'lower_wick_ticks': {'min': 0.0,
   '25%': 2.0,
   '50%': 6.0,
   '75%': 15.0,
   'max': 608.0},
  'body_pct': {'min': 0.0,
   '25%': 0.23684210520083102,
   '50%': 0.45454545433884297,
   '75%': 0.6666666655555555,
   'max': 0.9999999998979593},
  'upper_wick_pct': {'min': 0.0,
   '25%': 0.09999999996666667,
   '50%': 0.2222222220987654,
   '75%': 0.3913043476559546,

In [33]:
df_final.columns.tolist()

['datetime',
 'open',
 'high',
 'low',
 'close',
 'volume',
 'openint',
 'ticker',
 'per',
 'trading_date',
 'open_day',
 'high_cum',
 'low_cum',
 'volume_cum',
 'sma_20',
 'ema_20',
 'dema',
 'kama',
 'ema_fast',
 'ema_slow',
 'macd',
 'signal',
 'histogram',
 'adx',
 'rsi',
 'slowk',
 'slowd',
 'cmo',
 'williams_r',
 'cci',
 'roc_10',
 'roc_1',
 'roc_5',
 'roc_20',
 'bb_middle',
 'bb_std',
 'bb_upper',
 'bb_lower',
 'true_range',
 'range',
 'range_mean',
 'hv',
 'realized_vol_20',
 'obv',
 'obv_norm',
 'obv_roc_5',
 'obv_roc_10',
 'obv_ema_10',
 'obv_sma_10',
 'obv_z',
 'obv_dir',
 'obv_rel',
 'obv_delta',
 'vpt',
 'clv',
 'ad',
 'ad_norm',
 'ad_roc_5',
 'ad_roc_10',
 'ad_ema_10',
 'ad_sma_10',
 'ad_z',
 'ad_delta',
 'ad_dir',
 'ad_rel',
 'volume_range',
 'volume_price',
 'mfi',
 'cmf',
 'efi',
 'vwap',
 'avg_volume',
 'relative_volume',
 'volume_z',
 'volume_sum_20',
 'volume_delta',
 'pct_above_ma_20',
 'pct_above_ma_50',
 'slope_10',
 'tr_dir',
 'body',
 'wick_ratio',
 'is_doji',
 'body_ticks',
 'range_ticks',
 'upper_wick_ticks',
 'lower_wick_ticks',
 'body_pct',
 'upper_wick_pct',
 'lower_wick_pct',
 'close_location',
 'dist_high_cum_ticks',
 'dist_low_cum_ticks',
 'dist_open_day_ticks',
 'vol_per_tick',
 'vol_vs_body',
 'vol_weight_intraday',
 'hour',
 'minute',
 'dayofweek',
 'day',
 'month',
 'is_month_end',
 'hour_sin',
 'hour_cos',
 'minute_sin',
 'minute_cos',
 'dow_sin',
 'dow_cos',
 'day_sin',
 'day_cos',
 'month_sin',
 'month_cos',
 'is_prev_break_hour',
 'is_post_break_hour',
 'is_NY_open_hour',
 'week_of_month',
 'seconds_since_midnight',
 'session_progress',
 'is_london',
 'is_ny',
 'is_overlap',
 'return',
 'log_return',
 'return_horizon_2880m',
 'log_return_horizon_2880m',
 'return_lag_1',
 'return_lag_5',
 'return_lag_10',
 'return_lag_20',
 'return_mean_5',
 'return_std_5',
 'return_z_5',
 'return_mean_10',
 'return_std_10',
 'return_z_10',
 'return_mean_20',
 'return_std_20',
 'return_z_20',
 'swing_high',
 'swing_low',
 'swing_high_price',
 'swing_low_price',
 'swing_high_strength',
 'swing_low_strength',
 'last_swing_high_price',
 'last_swing_low_price',
 'last_swing_high_strength',
 'last_swing_low_strength',
 'last_swing_high_bar',
 'last_swing_low_bar',
 'bb_width',
 'bb_percent_b',
 'atr',
 'vpt_norm',
 'rolling_skew_10',
 'rolling_kurt_10',
 'rolling_skew_20',
 'rolling_kurt_20',
 'dist_to_last_swing_high',
 'dist_to_last_swing_low',
 'swing_range',
 'swing_range_pct',
 'bars_since_swing_high',
 'bars_since_swing_low',
 'close_in_swing_range',
 'swing_high_type',
 'swing_low_type',
 'market_structure',
 'swing_trend_score',
 'atr_norm',
 'atr_z',
 'vol_vol_ratio',
 'retracement_ratio',
 'fib_dist_236',
 'fib_dist_382',
 'fib_dist_5',
 'fib_dist_618',
 'fib_dist_786',
 'nearest_fib_level',
 'dist_to_nearest_fib',
 'swing_extension',
 'bars_between_swing_highs',
 'bars_between_swing_lows',
 'swing_high_velocity',
 'swing_low_velocity',
 'bars_between_swings',
 'swing_cycle_ratio']