In [1]:
from tradepy.data.loader import load_future
from tradepy.config.config import load_config, load_symbols, load_feature_config
from tradepy.data.cleaner import add_trading_date_by_gap
from tradepy.data.resampler import resample_ohlcv, daily_ohlcv_cummulative
from tradepy.features.generate import generate_features
from tradepy.features.quality_check import data_quality_report

In [2]:
symbols = load_symbols()

In [3]:
symbols

['AD',
 'BP',
 'CL',
 'EC',
 'ES',
 'GC',
 'MFXI',
 'NG',
 'NQ',
 'YM',
 'ZB',
 'ZN',
 'ZS']

In [4]:
ASSET = symbols[4]

In [5]:
cfg = load_config()

In [6]:
MINUTES             = cfg['sampling_minutes']        # 240
RETURN_HORIZON_MIN  = cfg['return_horizon_min']      # 2880

In [7]:
df, spec = load_future(ASSET)

In [8]:
df = add_trading_date_by_gap(df)

In [9]:
df

,ticker,per,date,time,open,high,low,close,volume,openint,datetime,session_id,trading_date
0,ES,I,1997-09-10,07:08:00,934.00,934.00,934.00,934.00,1,0,1997-09-10 07:08:00,0,1997-09-10
1,ES,I,1997-09-10,07:15:00,933.75,933.75,933.75,933.75,1,0,1997-09-10 07:15:00,0,1997-09-10
2,ES,I,1997-09-10,08:10:00,933.75,933.75,933.75,933.75,1,0,1997-09-10 08:10:00,0,1997-09-10
3,ES,I,1997-09-10,08:13:00,934.00,934.00,934.00,934.00,1,0,1997-09-10 08:13:00,0,1997-09-10
4,ES,I,1997-09-10,08:20:00,933.75,933.75,933.75,933.75,1,0,1997-09-10 08:20:00,0,1997-09-10
...,...,...,...,...,...,...,...,...,...,...,...,...,...
8631144,ES,I,2026-01-19,06:57:00,6917.00,6917.00,6916.75,6916.75,26,0,2026-01-19 06:57:00,5073,2026-01-19
8631145,ES,I,2026-01-19,06:58:00,6917.00,6917.00,6916.75,6917.00,33,0,2026-01-19 06:58:00,5073,2026-01-19
8631146,ES,I,2026-01-19,06:59:00,6917.00,6917.50,6916.75,6916.75,112,0,2026-01-19 06:59:00,5073,2026-01-19
8631147,ES,I,2026-01-19,07:00:00,6916.75,6917.00,6916.25,6916.75,64,0,2026-01-19 07:00:00,5073,2026-01-19
8631148,ES,I,2026-01-19,07:01:00,6916.75,6917.25,6916.50,6917.00,33,0,2026-01-19 07:01:00,5073,2026-01-19

In [10]:
df_resampled = resample_ohlcv(df, period=f"{MINUTES}min")
df_cumulative = daily_ohlcv_cummulative(df_resampled)

In [11]:
config = load_feature_config()

In [12]:
config["global"]["sampling_minutes"] = MINUTES
config["global"]["return_horizon_min"] = RETURN_HORIZON_MIN
config["global"]["tick_size"] = spec["tick_size"]

In [13]:
df_final = generate_features(df_cumulative, config)

In [14]:
df_final

,datetime,open,high,low,close,volume,openint,ticker,per,trading_date,...,fib_dist_786,nearest_fib_level,dist_to_nearest_fib,swing_extension,bars_between_swing_highs,bars_between_swing_lows,swing_high_velocity,swing_low_velocity,bars_between_swings,swing_cycle_ratio
0,1997-09-10 08:00:00,934.00,934.00,933.75,933.75,2,0.0,ES,240min,1997-09-10,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,1997-09-10 12:00:00,933.75,934.25,932.75,933.00,28,0.0,ES,240min,1997-09-10,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,1997-09-10 16:00:00,932.75,933.00,928.75,931.75,414,0.0,ES,240min,1997-09-10,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,1997-09-10 20:00:00,932.00,932.00,924.75,926.25,1373,0.0,ES,240min,1997-09-10,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,1997-09-11 00:00:00,926.00,930.25,914.50,914.75,1290,0.0,ES,240min,1997-09-10,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
42589,2026-01-16 16:00:00,7002.75,7004.25,6981.50,6982.00,228308,0.0,ES,240min,2026-01-16,...,-0.615412,0.236,-0.065412,-0.829412,13.0,7.0,7.230769,6.071429,1.0,3.000000
42590,2026-01-16 20:00:00,6982.00,6995.00,6960.50,6987.75,561713,0.0,ES,240min,2026-01-16,...,-0.382899,0.382,0.021101,-0.596899,4.0,7.0,8.062500,6.071429,3.0,0.000000
42591,2026-01-17 00:00:00,6988.00,6997.50,6973.50,6977.75,345435,0.0,ES,240min,2026-01-16,...,-0.692977,0.236,-0.142977,-0.906977,4.0,7.0,8.062500,6.071429,3.0,0.333333
42592,2026-01-19 04:00:00,6918.25,6935.00,6911.00,6922.00,70217,0.0,ES,240min,2026-01-19,...,-2.421659,0.236,-1.871659,-2.635659,4.0,7.0,8.062500,6.071429,3.0,0.666667
42593,2026-01-19 08:00:00,6922.00,6922.75,6912.50,6917.00,16690,0.0,ES,240min,2026-01-19,...,-2.576698,0.236,-2.026698,-2.790698,4.0,7.0,8.062500,6.071429,3.0,1.000000

In [15]:
data_quality_report(df_final)

Data Quality Report
 - rows: 42594, cols: 188
 - top 20 NaN fractions:
swing_low              0.847021
swing_low_price        0.847021
swing_low_strength     0.847021
swing_high             0.845847
swing_high_price       0.845847
swing_high_strength    0.845847
ad_z                   0.027938
cmf                    0.027915
ad_sma_10              0.014556
ad_roc_10              0.003193
ad_roc_5               0.003029
ad_delta               0.003005
ad_dir                 0.003005
ad_rel                 0.002418
close_location         0.001503
body_pct               0.001503
wick_ratio             0.001503
volume_range           0.001503
obv_norm               0.001503
ad                     0.001503
dtype: float64

Suggestions:
 - Many columns have >50% NaNs; consider dropping or re-engineering them.
 - Drop or fix constant columns: ['openint', 'ticker', 'per', 'minute', 'minute_sin', 'minute_cos', 'is_post_break_hour', 'is_NY_open_hour']
 - `rolling_slope` may be slow; consider vectorized replacement or numba.
 - To avoid fragmentation, build new columns in a dict and `pd.concat` once per group.

{'rows': 42594,
 'cols': 188,
 'na_fraction': {'swing_low': 0.847020707141851,
  'swing_low_price': 0.847020707141851,
  'swing_low_strength': 0.847020707141851,
  'swing_high': 0.8458468328872611,
  'swing_high_price': 0.8458468328872611,
  'swing_high_strength': 0.8458468328872611,
  'ad_z': 0.02793820725923839,
  'cmf': 0.027914729774146593,
  'ad_sma_10': 0.01455604075691412,
  'ad_roc_10': 0.0031929379724843876,
  'ad_roc_5': 0.0030285955768418085,
  'ad_delta': 0.003005118091750012,
  'ad_dir': 0.003005118091750012,
  'ad_rel': 0.0024181809644550877,
  'close_location': 0.001502559045875006,
  'body_pct': 0.001502559045875006,
  'wick_ratio': 0.001502559045875006,
  'volume_range': 0.001502559045875006,
  'obv_norm': 0.001502559045875006,
  'ad': 0.001502559045875006,
  'clv': 0.001502559045875006,
  'ad_norm': 0.001502559045875006,
  'upper_wick_pct': 0.001502559045875006,
  'lower_wick_pct': 0.001502559045875006,
  'pct_above_ma_50': 0.0011503967694980514,
  'relative_volume': 0.0009156219185800817,
  'obv_rel': 0.0009156219185800817,
  'volume_z': 0.0009156219185800817,
  'mfi': 0.0009156219185800817,
  'adx': 0.0006338920974785181,
  'swing_extension': 0.0005634596422031273,
  'fib_dist_236': 0.0005634596422031273,
  'fib_dist_786': 0.0005634596422031273,
  'fib_dist_618': 0.0005634596422031273,
  'retracement_ratio': 0.0005634596422031273,
  'dist_to_nearest_fib': 0.0005634596422031273,
  'nearest_fib_level': 0.0005634596422031273,
  'close_in_swing_range': 0.0005634596422031273,
  'fib_dist_382': 0.0005634596422031273,
  'fib_dist_5': 0.0005634596422031273,
  'return_lag_20': 0.0004930271869277363,
  'roc_20': 0.00046954970183593934,
  'realized_vol_20': 0.00046954970183593934,
  'hv': 0.00046954970183593934,
  'return_z_20': 0.00046954970183593934,
  'rolling_skew_20': 0.00046954970183593934,
  'return_std_20': 0.00046954970183593934,
  'return_mean_20': 0.00046954970183593934,
  'rolling_kurt_20': 0.00046954970183593934,
  'atr_z': 0.00046954970183593934,
  'bb_std': 0.0004460722167441424,
  'swing_low_velocity': 0.0004460722167441424,
  'avg_volume': 0.0004460722167441424,
  'bb_middle': 0.0004460722167441424,
  'bb_upper': 0.0004460722167441424,
  'bb_lower': 0.0004460722167441424,
  'cci': 0.0004460722167441424,
  'obv_z': 0.0004460722167441424,
  'volume_sum_20': 0.0004460722167441424,
  'sma_20': 0.0004460722167441424,
  'bb_percent_b': 0.0004460722167441424,
  'bb_width': 0.0004460722167441424,
  'pct_above_ma_20': 0.0004460722167441424,
  'swing_high_velocity': 0.0004225947316523454,
  'bars_between_swing_highs': 0.0004225947316523454,
  'slowd': 0.00039911724656054845,
  'slowk': 0.00039911724656054845,
  'swing_cycle_ratio': 0.0003521622763769545,
  'swing_range': 0.0003521622763769545,
  'last_swing_high_strength': 0.0003521622763769545,
  'last_swing_high_bar': 0.0003521622763769545,
  'bars_between_swings': 0.0003521622763769545,
  'bars_since_swing_high': 0.0003521622763769545,
  'swing_range_pct': 0.0003521622763769545,
  'dist_to_last_swing_high': 0.0003521622763769545,
  'last_swing_high_price': 0.0003521622763769545,
  'rsi': 0.00032868479128515755,
  'cmo': 0.00032868479128515755,
  'efi': 0.0003052073061933606,
  'range_mean': 0.0003052073061933606,
  'williams_r': 0.0003052073061933606,
  'return_horizon_2880m': 0.0002817298211015636,
  'log_return_horizon_2880m': 0.0002817298211015636,
  'return_lag_10': 0.0002582523360097666,
  'rolling_kurt_10': 0.00023477485091796967,
  'kama': 0.00023477485091796967,
  'obv_roc_10': 0.00023477485091796967,
  'roc_10': 0.00023477485091796967,
  'return_z_10': 0.00023477485091796967,
  'return_mean_10': 0.00023477485091796967,
  'rolling_skew_10': 0.00023477485091796967,
  'return_std_10': 0.00023477485091796967,
  'obv_sma_10': 0.0002112973658261727,
  'bars_between_swing_lows': 0.0002112973658261727,
  'slope_10': 0.0002112973658261727,
  'last_swing_low_strength': 0.0001408649105507818,
  'dist_to_last_swing_low': 0.0001408649105507818,
  'bars_since_swing_low': 0.0001408649105507818,
  'last_swing_low_price': 0.0001408649105507818,
  'return_lag_5': 0.0001408649105507818,
  'last_swing_low_bar': 0.0001408649105507818,
  'return_mean_5': 0.00011738742545898484,
  'return_z_5': 0.00011738742545898484,
  'return_std_5': 0.00011738742545898484,
  'roc_5': 0.00011738742545898484,
  'obv_roc_5': 0.00011738742545898484,
  'tr_dir': 4.6954970183593935e-05,
  'return_lag_1': 4.6954970183593935e-05,
  'vpt_norm': 2.3477485091796968e-05,
  'atr': 2.3477485091796968e-05,
  'atr_norm': 2.3477485091796968e-05,
  'vol_vol_ratio': 2.3477485091796968e-05,
  'log_return': 2.3477485091796968e-05,
  'obv_delta': 2.3477485091796968e-05,
  'return': 2.3477485091796968e-05,
  'volume_delta': 2.3477485091796968e-05,
  'obv_dir': 2.3477485091796968e-05,
  'roc_1': 2.3477485091796968e-05,
  'vpt': 2.3477485091796968e-05,
  'true_range': 2.3477485091796968e-05,
  'ema_20': 0.0,
  'histogram': 0.0,
  'macd': 0.0,
  'signal': 0.0,
  'ad_ema_10': 0.0,
  'obv_ema_10': 0.0,
  'range': 0.0,
  'obv': 0.0,
  'ticker': 0.0,
  'openint': 0.0,
  'volume': 0.0,
  'volume_cum': 0.0,
  'ema_slow': 0.0,
  'ema_fast': 0.0,
  'dema': 0.0,
  'close': 0.0,
  'datetime': 0.0,
  'open': 0.0,
  'high': 0.0,
  'low': 0.0,
  'high_cum': 0.0,
  'open_day': 0.0,
  'trading_date': 0.0,
  'per': 0.0,
  'low_cum': 0.0,
  'seconds_since_midnight': 0.0,
  'is_post_break_hour': 0.0,
  'week_of_month': 0.0,
  'is_ny': 0.0,
  'is_overlap': 0.0,
  'session_progress': 0.0,
  'is_london': 0.0,
  'dist_open_day_ticks': 0.0,
  'dist_low_cum_ticks': 0.0,
  'range_ticks': 0.0,
  'dist_high_cum_ticks': 0.0,
  'volume_price': 0.0,
  'body': 0.0,
  'upper_wick_ticks': 0.0,
  'lower_wick_ticks': 0.0,
  'is_doji': 0.0,
  'vwap': 0.0,
  'body_ticks': 0.0,
  'is_NY_open_hour': 0.0,
  'month_sin': 0.0,
  'day_cos': 0.0,
  'is_prev_break_hour': 0.0,
  'month_cos': 0.0,
  'day_sin': 0.0,
  'dow_cos': 0.0,
  'minute_cos': 0.0,
  'dow_sin': 0.0,
  'dayofweek': 0.0,
  'minute': 0.0,
  'minute_sin': 0.0,
  'hour_cos': 0.0,
  'hour_sin': 0.0,
  'is_month_end': 0.0,
  'month': 0.0,
  'day': 0.0,
  'vol_vs_body': 0.0,
  'vol_per_tick': 0.0,
  'hour': 0.0,
  'vol_weight_intraday': 0.0,
  'market_structure': 0.0,
  'swing_trend_score': 0.0,
  'swing_high_type': 0.0,
  'swing_low_type': 0.0},
 'top_na': {'swing_low': 0.847020707141851,
  'swing_low_price': 0.847020707141851,
  'swing_low_strength': 0.847020707141851,
  'swing_high': 0.8458468328872611,
  'swing_high_price': 0.8458468328872611,
  'swing_high_strength': 0.8458468328872611,
  'ad_z': 0.02793820725923839,
  'cmf': 0.027914729774146593,
  'ad_sma_10': 0.01455604075691412,
  'ad_roc_10': 0.0031929379724843876,
  'ad_roc_5': 0.0030285955768418085,
  'ad_delta': 0.003005118091750012,
  'ad_dir': 0.003005118091750012,
  'ad_rel': 0.0024181809644550877,
  'close_location': 0.001502559045875006,
  'body_pct': 0.001502559045875006,
  'wick_ratio': 0.001502559045875006,
  'volume_range': 0.001502559045875006,
  'obv_norm': 0.001502559045875006,
  'ad': 0.001502559045875006},
 'constant_columns': ['openint',
  'ticker',
  'per',
  'minute',
  'minute_sin',
  'minute_cos',
  'is_post_break_hour',
  'is_NY_open_hour'],
 'infinite_columns': [],
 'infinite_counts': {},
 'top_zero_fraction': {'openint': 1.0,
  'minute_sin': 1.0,
  'minute': 1.0,
  'is_doji': 0.8953843264309527,
  'is_overlap': 0.828755223740433,
  'is_ny': 0.6578156547870592,
  'is_london': 0.49030379865708784,
  'market_structure': 0.3550265295581537,
  'swing_trend_score': 0.2703667183171339,
  'hour': 0.16762924355543035,
  'session_progress': 0.16762924355543035,
  'seconds_since_midnight': 0.16762924355543035,
  'hour_sin': 0.16762924355543035,
  'dow_sin': 0.16673709912194207,
  'dayofweek': 0.16673709912194207,
  'bars_since_swing_high': 0.15415316711273888,
  'bars_since_swing_low': 0.15297929285814904,
  'swing_cycle_ratio': 0.1446682631356529,
  'month_sin': 0.08210076536601399,
  'lower_wick_ticks': 0.06331877729257641},
 'object_unique_counts': {'ticker': 1, 'per': 1, 'trading_date': 7400},
 'describe': {'datetime': {'min': Timestamp('1997-09-10 08:00:00'),
   '25%': Timestamp('2005-04-27 17:00:00'),
   '50%': Timestamp('2012-03-29 10:00:00'),
   '75%': Timestamp('2019-02-20 07:00:00'),
   'max': Timestamp('2026-01-19 08:00:00')},
  'open': {'min': 671.5,
   '25%': 1192.0,
   '50%': 1475.5,
   '75%': 2820.5,
   'max': 7016.0},
  'high': {'min': 679.75,
   '25%': 1195.25,
   '50%': 1479.0,
   '75%': 2828.75,
   'max': 7036.25},
  'low': {'min': 665.75,
   '25%': 1188.75,
   '50%': 1471.0,
   '75%': 2812.9375,
   'max': 7009.75},
  'close': {'min': 671.5,
   '25%': 1192.0,
   '50%': 1475.25,
   '75%': 2820.9375,
   'max': 7016.0},
  'volume': {'min': 0.0,
   '25%': 11380.0,
   '50%': 58512.0,
   '75%': 317702.0,
   'max': 3274653.0},
  'openint': {'min': 0.0, '25%': 0.0, '50%': 0.0, '75%': 0.0, 'max': 0.0},
  'open_day': {'min': 675.0,
   '25%': 1192.5,
   '50%': 1475.25,
   '75%': 2820.875,
   'max': 7014.0},
  'high_cum': {'min': 679.75,
   '25%': 1196.5,
   '50%': 1480.5,
   '75%': 2833.25,
   'max': 7036.25},
  'low_cum': {'min': 665.75,
   '25%': 1187.25,
   '50%': 1468.5,
   '75%': 2809.5,
   'max': 6998.75},
  'volume_cum': {'min': 0.0,
   '25%': 18046.5,
   '50%': 95270.0,
   '75%': 607345.75,
   'max': 6267746.0},
  'sma_20': {'min': 686.1875,
   '25%': 1191.99375,
   '50%': 1472.9625,
   '75%': 2822.45,
   'max': 6991.0375},
  'ema_20': {'min': 687.5153953992241,
   '25%': 1192.062484977671,
   '50%': 1472.4849905376798,
   '75%': 2820.5112588515353,
   'max': 6990.463198956946},
  'dema': {'min': 675.1142208190888,
   '25%': 1191.934633155337,
   '50%': 1474.1548074093234,
   '75%': 2821.7075505704056,
   'max': 7005.914991154401},
  'kama': {'min': 689.6416052456585,
   '25%': 1192.3896298295776,
   '50%': 1474.8541617373858,
   '75%': 2816.25139705525,
   'max': 6986.521827127014},
  'ema_fast': {'min': 682.7990893974779,
   '25%': 1191.7154952404858,
   '50%': 1473.301363450354,
   '75%': 2822.3908364622775,
   'max': 6997.104587034471},
  'ema_slow': {'min': 691.4748571715934,
   '25%': 1192.3258822884302,
   '50%': 1472.7717210085434,
   '75%': 2819.953689800105,
   'max': 6986.32426850824},
  'macd': {'min': -173.89594743012367,
   '25%': -3.4309510972218504,
   '50%': 1.6585909255845763,
   '75%': 5.852558591865829,
   'max': 60.64243997813537},
  'signal': {'min': -139.06661790837788,
   '25%': -3.1301310740849715,
   '50%': 1.5908057873381662,
   '75%': 5.499574656853124,
   'max': 55.67673000124055},
  'histogram': {'min': -56.44652118246135,
   '25%': -1.4040142116316678,
   '50%': -0.07699436801595472,
   '75%': 1.3217540808869288,
   'max': 68.30554576959156},
  'adx': {'min': 5.374953089693972,
   '25%': 18.931551705744866,
   '50%': 24.311002308205104,
   '75%': 31.510855347353807,
   'max': 74.8776533687409},
  'rsi': {'min': 6.228793981431889,
   '25%': 43.090127022680086,
   '50%': 53.470704075493245,
   '75%': 62.296712751949585,
   'max': 88.42529258187982},
  'slowk': {'min': 5.944874222526172e-13,
   '25%': 30.768080276763015,
   '50%': 60.24838945341065,
   '75%': 82.95967227039995,
   'max': 100.00000000000023},
  'slowd': {'min': 1.2132675384618756,
   '25%': 31.4814814814812,
   '50%': 60.16201706451894,
   '75%': 82.25034978215626,
   'max': 99.09581339629638},
  'cmo': {'min': -99.15966386554622,
   '25%': -21.290796267348775,
   '50%': 6.077348066298343,
   '75%': 33.247531495771796,
   'max': 100.0},
  'williams_r': {'min': -100.0,
   '25%': -70.6896551724138,
   '50%': -39.34426229508197,
   '75%': -15.32567049808429,
   'max': -0.0},
  'cci': {'min': -600.4088839327244,
   '25%': -75.39387767489166,
   '50%': 29.723394280358466,
   '75%': 98.4159361517807,
   'max': 474.89046174587475},
  'roc_10': {'min': -0.1481924826430453,
   '25%': -0.006209427204150936,
   '50%': 0.0012191068620192036,
   '75%': 0.008038208959135706,
   'max': 0.21007910928801632},
  'roc_1': {'min': -0.06210986267166041,
   '25%': -0.0014998125234345627,
   '50%': 0.00014928158238469713,
   '75%': 0.0017939901330543684,
   'max': 0.071070480684164},
  'roc_5': {'min': -0.11853340030135606,
   '25%': -0.0043591979075849885,
   '50%': 0.0006485084306095956,
   '75%': 0.005357142857142838,
   'max': 0.1145838635785188},
  'roc_20': {'min': -0.189696106362773,
   '25%': -0.008629103674268473,
   '50%': 0.002453771875324029,
   '75%': 0.01198767099355219,
   'max': 0.17245989304812825},
  'bb_middle': {'min': 686.1875,
   '25%': 1191.99375,
   '50%': 1472.9625,
   '75%': 2822.45,
   'max': 6991.0375},
  'bb_std': {'min': 0.8170671263480527,
   '25%': 6.110145791528305,
   '50%': 9.857963322520265,
   '75%': 17.571121924089788,
   'max': 252.62821002441882},
  'bb_upper': {'min': 702.9150969576486,
   '25%': 1208.2489015799692,
   '50%': 1496.1549955707346,
   '75%': 2856.8358004262705,
   'max': 7034.634279297703},
  'bb_lower': {'min': 658.2716707546621,
   '25%': 1176.3415909066625,
   '50%': 1454.9138993112251,
   '75%': 2787.4968582879,
   'max': 6952.564585735003},
  'true_range': {'min': 0.0,
   '25%': 4.25,
   '50%': 8.0,
   '75%': 14.5,
   'max': 440.5},
  'range': {'min': 0.0, '25%': 4.25, '50%': 7.75, '75%': 14.5, 'max': 440.5},
  'range_mean': {'min': 2.0714285714285716,
   '25%': 5.732142857142857,
   '50%': 8.232142857142858,
   '75%': 14.214285714285714,
   'max': 163.75},
  'hv': {'min': 0.0077771744566696365,
   '25%': 0.03646151401412293,
   '50%': 0.05330518656082123,
   '75%': 0.07826980822773881,
   'max': 0.47471727568638106},
  'realized_vol_20': {'min': 0.0076032139941577415,
   '25%': 0.036626008915065865,
   '50%': 0.05329921373392828,
   '75%': 0.07834769980075408,
   'max': 0.4630001432349108},
  'obv': {'min': -41237187.0,
   '25%': -4295.25,
   '50%': 10449482.5,
   '75%': 60640693.75,
   'max': 131984417.0},
  'obv_norm': {'min': -23945644.0,
   '25%': -657.3791425965339,
   '50%': 1812347.9105590063,
   '75%': 5107874.399380805,
   'max': 146962300.0},
  'obv_roc_5': {'min': -2821.0,
   '25%': -0.023692122265038917,
   '50%': 0.000674556081371902,
   '75%': 0.024484548052180255,
   'max': 2115.0},
  'obv_roc_10': {'min': -2379.3333333333335,
   '25%': -0.034362694315356435,
   '50%': 0.0015120777485548853,
   '75%': 0.03416301428539498,
   'max': 3886.8333333333335},
  'obv_ema_10': {'min': -39941044.82564128,
   '25%': -3814.7655617319083,
   '50%': 10344095.858677704,
   '75%': 60626768.66298239,
   'max': 131583567.06494111},
  'obv_sma_10': {'min': -40022560.9,
   '25%': -3886.3,
   '50%': 10363005.8,
   '75%': 60603905.4,
   'max': 131709962.8},
  'obv_z': {'min': -4.248529157248015,
   '25%': -0.9667614457223257,
   '50%': 0.21033897177289299,
   '75%': 1.1754553349067995,
   'max': 4.233061181756779},
  'obv_dir': {'min': -1.0, '25%': -1.0, '50%': 1.0, '75%': 1.0, 'max': 1.0},
  'obv_rel': {'min': -85.12376030702588,
   '25%': -0.032007086743412655,
   '50%': 3.0905737619855644,
   '75%': 13.338651419056589,
   'max': 76.575581477156},
  'obv_delta': {'min': -2902700.0,
   '25%': -47352.0,
   '50%': 25.0,
   '75%': 65389.0,
   'max': 3274653.0},
  'vpt': {'min': -109112.07164790174,
   '25%': -65.71740827478533,
   '50%': 0.03296703296703297,
   '75%': 108.0998248686515,
   'max': 126832.59304040107},
  'clv': {'min': -1.0,
   '25%': -0.47368421052631576,
   '50%': 0.07692307692307693,
   '75%': 0.6,
   'max': 1.0},
  'ad': {'min': -938551.4758304463,
   '25%': 11820327.139722044,
   '50%': 91493309.60099757,
   '75%': 259539710.80117285,
   'max': 425816457.39007086},
  'ad_norm': {'min': -448713.04738234973,
   '25%': 2011894.8837472086,
   '50%': 9833387.204857556,
   '75%': 22309632.961983405,
   'max': 709031630.8482099},
  'ad_roc_5': {'min': -37.92566725593687,
   '25%': -0.0025060367983777976,
   '50%': 0.00048713896807806023,
   '75%': 0.00464176038051356,
   'max': 954.0528832222544},
  'ad_roc_10': {'min': -30.675632906421658,
   '25%': -0.0032408514105415342,
   '50%': 0.000922402765305752,
   '75%': 0.007014392872114417,
   'max': 1088.8072843766554},
  'ad_ema_10': {'min': -722331.9070847105,
   '25%': 11798743.443763608,
   '50%': 91389512.60368243,
   '75%': 258730869.750408,
   'max': 425508655.3131691},
  'ad_sma_10': {'min': -721581.5890626229,
   '25%': 12046415.147243168,
   '50%': 92936657.47905037,
   '75%': 260572579.91239375,
   'max': 425519938.22563535},
  'ad_z': {'min': -4.248529157249601,
   '25%': -0.7307663043503702,
   '50%': 0.5139462347689797,
   '75%': 1.3152347291811166,
   'max': 3.8871852214707587},
  'ad_delta': {'min': -2276804.838926181,
   '25%': -16480.220168069005,
   '50%': 90.125,
   '75%': 32429.75148808956,
   'max': 2576503.629441619},
  'ad_dir': {'min': -1.0, '25%': -1.0, '50%': 1.0, '75%': 1.0, 'max': 1.0},
  'ad_rel': {'min': -1.3445532717320998,
   '25%': 4.229010737295688,
   '50%': 15.114301376909484,
   '75%': 56.58944984989711,
   'max': 275.7588161013537},
  'volume_range': {'min': 0.0,
   '25%': 2105.2410714285716,
   '50%': 6436.866760168303,
   '75%': 26185.318279569892,
   'max': 188237.88235294117},
  'volume_price': {'min': 0.0,
   '25%': 5.363852860999986,
   '50%': 27.66518056857966,
   '75%': 145.7500094612471,
   'max': 2789.75681218869},
  'mfi': {'min': 0.0,
   '25%': 34.83392813164202,
   '50%': 51.017772840460886,
   '75%': 67.82329979694421,
   'max': 100.0},
  'cmf': {'min': -0.7001043384584398,
   '25%': -0.0771672814186746,
   '50%': 0.06294518662730882,
   '75%': 0.1998322328326188,
   'max': 0.7181744365389302},
  'efi': {'min': -45880188.15250533,
   '25%': -313826.992173621,
   '50%': 7406.106598126353,
   '75%': 379650.0838962482,
   'max': 54832582.89394121},
  'vwap': {'min': 921.6835939402796,
   '25%': 1161.3464939004532,
   '50%': 1256.388430404027,
   '75%': 1550.6945488097012,
   'max': 2316.4490060340877},
  'avg_volume': {'min': 0.0,
   '25%': 114316.7,
   '50%': 195396.85,
   '75%': 276556.175,
   'max': 1119736.65},
  'relative_volume': {'min': 0.0,
   '25%': 0.08252980906330974,
   '50%': 0.4866890974558763,
   '75%': 1.6650095479840912,
   'max': 20.0},
  'volume_z': {'min': -1.1992406589697844,
   '25%': -0.7755714496527256,
   '50%': -0.4458333797300968,
   '75%': 0.6565430759774257,
   'max': 4.2485291572496005},
  'volume_sum_20': {'min': 0.0,
   '25%': 2286334.0,
   '50%': 3907937.0,
   '75%': 5531123.5,
   'max': 22394733.0},
  'volume_delta': {'min': -2830311.0,
   '25%': -75676.0,
   '50%': 1070.0,
   '75%': 115344.0,
   'max': 1905454.0},
  'pct_above_ma_20': {'min': -0.11731236745461127,
   '25%': -0.004836587231834143,
   '50%': 0.001351438316494022,
   '75%': 0.006545625381225391,
   'max': 0.10340262147491062},
  'pct_above_ma_50': {'min': -0.1949826165305708,
   '25%': -0.007229218615761792,
   '50%': 0.0032896790222100036,
   '75%': 0.011137108235246614,
   'max': 0.09538426795250857},
  'slope_10': {'min': -69.56666666666666,
   '25%': -1.5742424242424242,
   '50%': -0.21666666666666667,
   '75%': 1.2181818181818183,
   'max': 65.76666666666667},
  'tr_dir': {'min': -1.0, '25%': -1.0, '50%': 1.0, '75%': 1.0, 'max': 1.0},
  'body': {'min': 0.0, '25%': 1.0, '50%': 3.0, '75%': 7.0, 'max': 347.0},
  'wick_ratio': {'min': 0.0,
   '25%': 0.3409090909090909,
   '50%': 0.55,
   '75%': 0.7666666666666667,
   'max': 1.0},
  'is_doji': {'min': 0.0, '25%': 0.0, '50%': 0.0, '75%': 0.0, 'max': 1.0},
  'body_ticks': {'min': -790.0,
   '25%': -10.0,
   '50%': 1.0,
   '75%': 13.0,
   'max': 1388.0},
  'range_ticks': {'min': 0.0,
   '25%': 17.0,
   '50%': 31.0,
   '75%': 58.0,
   'max': 1762.0},
  'upper_wick_ticks': {'min': 0.0,
   '25%': 2.0,
   '50%': 6.0,
   '75%': 14.0,
   'max': 585.0},
  'lower_wick_ticks': {'min': 0.0,
   '25%': 3.0,
   '50%': 7.0,
   '75%': 16.0,
   'max': 649.0},
  'body_pct': {'min': 0.0,
   '25%': 0.23333333325555555,
   '50%': 0.449999999775,
   '75%': 0.6590909089411157,
   'max': 0.9999999999742268},
  'upper_wick_pct': {'min': 0.0,
   '25%': 0.09999999995,
   '50%': 0.2222222220987654,
   '75%': 0.3976930448610275,

In [16]:
df_final.columns.tolist()

['datetime',
 'open',
 'high',
 'low',
 'close',
 'volume',
 'openint',
 'ticker',
 'per',
 'trading_date',
 'open_day',
 'high_cum',
 'low_cum',
 'volume_cum',
 'sma_20',
 'ema_20',
 'dema',
 'kama',
 'ema_fast',
 'ema_slow',
 'macd',
 'signal',
 'histogram',
 'adx',
 'rsi',
 'slowk',
 'slowd',
 'cmo',
 'williams_r',
 'cci',
 'roc_10',
 'roc_1',
 'roc_5',
 'roc_20',
 'bb_middle',
 'bb_std',
 'bb_upper',
 'bb_lower',
 'true_range',
 'range',
 'range_mean',
 'hv',
 'realized_vol_20',
 'obv',
 'obv_norm',
 'obv_roc_5',
 'obv_roc_10',
 'obv_ema_10',
 'obv_sma_10',
 'obv_z',
 'obv_dir',
 'obv_rel',
 'obv_delta',
 'vpt',
 'clv',
 'ad',
 'ad_norm',
 'ad_roc_5',
 'ad_roc_10',
 'ad_ema_10',
 'ad_sma_10',
 'ad_z',
 'ad_delta',
 'ad_dir',
 'ad_rel',
 'volume_range',
 'volume_price',
 'mfi',
 'cmf',
 'efi',
 'vwap',
 'avg_volume',
 'relative_volume',
 'volume_z',
 'volume_sum_20',
 'volume_delta',
 'pct_above_ma_20',
 'pct_above_ma_50',
 'slope_10',
 'tr_dir',
 'body',
 'wick_ratio',
 'is_doji',
 'body_ticks',
 'range_ticks',
 'upper_wick_ticks',
 'lower_wick_ticks',
 'body_pct',
 'upper_wick_pct',
 'lower_wick_pct',
 'close_location',
 'dist_high_cum_ticks',
 'dist_low_cum_ticks',
 'dist_open_day_ticks',
 'vol_per_tick',
 'vol_vs_body',
 'vol_weight_intraday',
 'hour',
 'minute',
 'dayofweek',
 'day',
 'month',
 'is_month_end',
 'hour_sin',
 'hour_cos',
 'minute_sin',
 'minute_cos',
 'dow_sin',
 'dow_cos',
 'day_sin',
 'day_cos',
 'month_sin',
 'month_cos',
 'is_prev_break_hour',
 'is_post_break_hour',
 'is_NY_open_hour',
 'week_of_month',
 'seconds_since_midnight',
 'session_progress',
 'is_london',
 'is_ny',
 'is_overlap',
 'return',
 'log_return',
 'return_horizon_2880m',
 'log_return_horizon_2880m',
 'return_lag_1',
 'return_lag_5',
 'return_lag_10',
 'return_lag_20',
 'return_mean_5',
 'return_std_5',
 'return_z_5',
 'return_mean_10',
 'return_std_10',
 'return_z_10',
 'return_mean_20',
 'return_std_20',
 'return_z_20',
 'swing_high',
 'swing_low',
 'swing_high_price',
 'swing_low_price',
 'swing_high_strength',
 'swing_low_strength',
 'last_swing_high_price',
 'last_swing_low_price',
 'last_swing_high_strength',
 'last_swing_low_strength',
 'last_swing_high_bar',
 'last_swing_low_bar',
 'bb_width',
 'bb_percent_b',
 'atr',
 'vpt_norm',
 'rolling_skew_10',
 'rolling_kurt_10',
 'rolling_skew_20',
 'rolling_kurt_20',
 'dist_to_last_swing_high',
 'dist_to_last_swing_low',
 'swing_range',
 'swing_range_pct',
 'bars_since_swing_high',
 'bars_since_swing_low',
 'close_in_swing_range',
 'swing_high_type',
 'swing_low_type',
 'market_structure',
 'swing_trend_score',
 'atr_norm',
 'atr_z',
 'vol_vol_ratio',
 'retracement_ratio',
 'fib_dist_236',
 'fib_dist_382',
 'fib_dist_5',
 'fib_dist_618',
 'fib_dist_786',
 'nearest_fib_level',
 'dist_to_nearest_fib',
 'swing_extension',
 'bars_between_swing_highs',
 'bars_between_swing_lows',
 'swing_high_velocity',
 'swing_low_velocity',
 'bars_between_swings',
 'swing_cycle_ratio']